### PR TITLE
Fix/bg color login form

### LINKED ISSUE #292: layout: fix background color on login form fields
The form fields color in the login page are wrong for me at least.   

image

### PR DESCRIPTION
**Pull request by PedroOliveira42**
Closes #292 

Altered the login forms to not use the browsers autofill style changes.

## Before
image

## After
image

# Potencial Problems
This will make it so that every input field with autofill will have a pink background and letters, will most likely not become an issue though because few fields with autofill options will have diferent background options. However cresting a custom class for pink autofill inputs could also be done.

### CODE REVIEW

File: src/routes/(app)/+layout.svelte [hunk 1]
```diff
@@ -32,4 +32,15 @@
     flex-direction: column;
     overflow: auto;
   }
+
+  :global(
```
Comment (rubuy-74) [inline src/routes/(app)/+layout.svelte:40]: Just a minor thing, it would be good to have a little bit more context. For people that could end up having the problems that you mentioned in the PR's description.

**Review by rubuy-74 — CHANGES_REQUESTED** [review]

**Review by rubuy-74 — APPROVED** [review]
Nice work :rocket:
